/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  PC02
 * Created: 22-abr-2019
 */




CREATE TABLE DESARROLLADORA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGO_DESARROLLADORA INTEGER NOT NULL,
    FECHA_CREACION_EMPRESA DATE,
    NOMBRE VARCHAR(20) NOT NULL,
    CONSTRAINT ID_DESARROLLADORA_PK PRIMARY KEY (ID)   
);

CREATE TABLE JUEGO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL,
    GENERO VARCHAR(40) NOT NULL,
    CODIGO VARCHAR(20)NOT NULL,
    CODIGO_DESARROLLADORA INTEGER NOT NULL,
    DESCRIPCION VARCHAR(10000),
    PAIS_DESARROLADOR INTEGER NOT NULL,
    FECHA_CREACION DATE,
    FECHA_SALIDA DATE,
    NUM_DESARROLLADORES SMALLINT,
    PRESUPUESTO DECIMAL(15,2),
    STOCK BOOLEAN,
    FOTO VARCHAR(30)NOT NULL,
    CONSTRAINT ID_JUEGO_PK PRIMARY KEY (ID),
    CONSTRAINT CODIGO_DESARROLLADORA_FK FOREIGN KEY (CODIGO_DESARROLLADORA) REFERENCES DESARROLLADORA (ID)
);


